// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC81TG70S4cxw08BRDAKrSvRBrPonvfxTg',
    appId: '1:190895267247:web:asso',
    messagingSenderId: '190895267247',
    projectId: 'asso-27ba4',
    authDomain: 'asso-27ba4.firebaseapp.com',
    storageBucket: 'asso-27ba4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnP2PwED24w-J6S88b-ronh1AGszQJzRM',
    appId: '1:190895267247:android:e038e53dfbfdd41dff235a',
    messagingSenderId: '190895267247',
    projectId: 'asso-27ba4',
    storageBucket: 'asso-27ba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC81TG70S4cxw08BRDAKrSvRBrPonvfxTg',
    appId: '1:190895267247:ios:2355a209a2c63f1fff235a',
    messagingSenderId: '190895267247',
    projectId: 'asso-27ba4',
    storageBucket: 'asso-27ba4.firebasestorage.app',
    iosBundleId: 'com.asso.asso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC81TG70S4cxw08BRDAKrSvRBrPonvfxTg',
    appId: '1:190895267247:ios:2355a209a2c63f1fff235a',
    messagingSenderId: '190895267247',
    projectId: 'asso-27ba4',
    storageBucket: 'asso-27ba4.firebasestorage.app',
    iosBundleId: 'com.asso.asso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC81TG70S4cxw08BRDAKrSvRBrPonvfxTg',
    appId: '1:190895267247:windows:asso',
    messagingSenderId: '190895267247',
    projectId: 'asso-27ba4',
    authDomain: 'asso-27ba4.firebaseapp.com',
    storageBucket: 'asso-27ba4.firebasestorage.app',
  );
}
